lizi_n: 2 # The number of Lizi robots

joy_for: 3 # Axis for forward motion.
joy_rot: 2 # Axis for rotation motion.
joy_pan: 0 # Axis for pan control.
joy_tilt: 1 # Axis for tilt control.
joy_scroll_btn: 5 # button for switching between Lizi robots.

max_vel: 1.0 # Maximum forward velocity (m/s)
max_rot: 3.0 # Maximum rotation velocity (rad/s)
max_pan: 0.6 # Maximum pan angle (+- rad)
max_tilt: 0.5 # Maximum tilt angle (+- rad)