closeLoop0/publishHz: 50
closeLoop0/name: RiC_Close_Motor0
closeLoop0/LPFAlpha: 0.7
closeLoop0/LPFHz: 50
closeLoop0/driverAddress: 128
closeLoop0/channel: 1
closeLoop0/port: 1
closeLoop0/PIDHz: 1000
closeLoop0/kP: 3.0
closeLoop0/kI: 3.0
closeLoop0/kD: 0
closeLoop0/limit: 1.0
closeLoop0/maxSpeed: 16.0
closeLoop0/cpr: 4480
closeLoop0/timeout: 1000
closeLoop0/motorType: 1
closeLoop0/direction: 1
closeLoop0/directionE: 1
closeLoop1/publishHz: 50
closeLoop1/name: RiC_Close_Motor1
closeLoop1/LPFAlpha: 0.7
closeLoop1/LPFHz: 50
closeLoop1/driverAddress: 128
closeLoop1/channel: 1
closeLoop1/port: 2
closeLoop1/PIDHz: 1000
closeLoop1/kP: 3.0
closeLoop1/kI: 3.0
closeLoop1/kD: 0
closeLoop1/limit: 1.0
closeLoop1/maxSpeed: 16.0
closeLoop1/cpr: 4480
closeLoop1/timeout: 1000
closeLoop1/motorType: 1
closeLoop1/direction: 1
closeLoop1/directionE: 1
closeLoop2/publishHz: 50
closeLoop2/name: RiC_Close_Motor2
closeLoop2/LPFAlpha: 0.7
closeLoop2/LPFHz: 50
closeLoop2/driverAddress: 128
closeLoop2/channel: 1
closeLoop2/port: 3
closeLoop2/PIDHz: 1000
closeLoop2/kP: 3.0
closeLoop2/kI: 3.0
closeLoop2/kD: 0
closeLoop2/limit: 1.0
closeLoop2/maxSpeed: 16.0
closeLoop2/cpr: 4480
closeLoop2/timeout: 1000
closeLoop2/motorType: 1
closeLoop2/direction: 1
closeLoop2/directionE: 1
closeLoop3/publishHz: 50
closeLoop3/name: RiC_Close_Motor3
closeLoop3/LPFAlpha: 0.7
closeLoop3/LPFHz: 50
closeLoop3/driverAddress: 128
closeLoop3/channel: 1
closeLoop3/port: 4
closeLoop3/PIDHz: 1000
closeLoop3/kP: 3.0
closeLoop3/kI: 3.0
closeLoop3/kD: 0
closeLoop3/limit: 1.0
closeLoop3/maxSpeed: 16.0
closeLoop3/cpr: 4480
closeLoop3/timeout: 1000
closeLoop3/motorType: 1
closeLoop3/direction: 1
closeLoop3/directionE: 1
Diff/publishHz: 50
Diff/name: Diff_driver
Diff/rWheel: 0.07
Diff/width: 0.255
Diff/baseLink: base_link
Diff/odom: odom_link
Diff/slip: 0.85
Diff/maxAng: 16.0
Diff/maxLin: 16.0
Diff/motorFL: 2
Diff/motorFR: 0
Diff/motorBL: 3
Diff/motorBR: 1
IMU_INIT: 0
GPS_INIT: 0
PPM_INIT: 0
BAT_INIT: 0
DIFF_INIT: 0
DIFF_INIT_OP: 0
DIFF_CLOSE_FOUR: 1
closeLoopNum: 4
switchNum: 0
servoNum: 0
relayNum: 0
URFNum: 0
openLoopNum: 0
