obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.5, -0.5], [-0.5, 0.5], [0.5, 0.5], [0.5,-0.5]]
inflation_radius: 0.05
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: Laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
