komodo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Trajectory Controllers ---------------------------------------
  arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - komodo_base_rotation_joint
      - komodo_shoulder_joint
      - komodo_elbow1_joint
      - komodo_elbow2_joint
      - komodo_wrist_joint
  gains:
    komodo_base_rotation_joint: {p: 400.0, d: 0.0, i: 0.0, i_clamp: 0.0} 
    komodo_shoulder_joint: {p: 400.0, d: 0.0, i: 0.0, i_clamp: 0.0} 
    komodo_elbow1_joint: {p: 700.0, d: 0.0, i: 0.0, i_clamp: 0.0}  
    komodo_elbow2_joint: {p: 700.0, d: 0.0, i: 0.0, i_clamp: 0.0}  
    komodo_wrist_joint: {p: 400.0, d: 0.0, i: 0.0, i_clamp: 0.0}
      

